# Generated by Django 5.2.17 on 2026-09-26 04:37

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=32)),
                ('broker_execution_id', models.CharField(blank=True, max_length=128, null=True)),
                ('broker_account_label', models.CharField(blank=True, default='', max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('contract_multiplier', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency', models.CharField(max_length=3)),
                ('executed_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'unscoped',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('raw_file', models.BinaryField(max_length=10485760)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'unscoped',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('rules_followed', models.BooleanField(blank=True, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('planned_risk_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('risk_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_execution', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='journal_entry', to='journal.execution')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'unscoped',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RawImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('raw', models.JSONField()),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('skipped_duplicate', 'Skipped (duplicate)'), ('failed', 'Failed')], max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='journal.importbatch')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'unscoped',
                'default_manager_name': 'unscoped',
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='raw_import_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='journal.rawimportrow'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['user', '-uploaded_at'], name='importbatch_user_uploaded_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('raw_file'), 10485760), name='importbatch_raw_file_size_limit'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'rules_followed'], name='journalentry_user_flag_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('planned_risk_amount__isnull', True), ('risk_currency__isnull', True)), models.Q(('planned_risk_amount__isnull', False), ('risk_currency__isnull', False), models.Q(('risk_currency', ''), _negated=True)), _connector='OR'), name='journalentry_risk_currency_required_with_amount'),
        ),
        migrations.AddIndex(
            model_name='rawimportrow',
            index=models.Index(fields=['user'], name='rawimportrow_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawimportrow',
            constraint=models.UniqueConstraint(fields=('import_batch', 'line_number'), name='rawimportrow_batch_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rawimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['imported', 'skipped_duplicate', 'failed'])), name='rawimportrow_status_valid'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['user', 'symbol', 'executed_at'], name='execution_user_symbol_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['user', '-executed_at'], name='execution_user_ts_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_execution_id__isnull', False), models.Q(('broker_execution_id', ''), _negated=True)), fields=('user', 'broker', 'broker_execution_id'), name='execution_broker_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['buy', 'sell'])), name='execution_side_valid'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='execution_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('price', 0), _negated=True), name='execution_price_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['manual', 'import'])), name='execution_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('contract_multiplier__gt', 0)), name='execution_contract_multiplier_positive'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='execution_currency_not_blank'),
        ),
    ]
