# Generated by Django 5.2.17 on 2026-09-26 05:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency must be a 3-letter uppercase ISO 4217 code, e.g. USD.')]),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='risk_currency',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency must be a 3-letter uppercase ISO 4217 code, e.g. USD.')]),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='execution_currency_iso_format'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'import'), _negated=True), models.Q(('broker_execution_id__isnull', False), models.Q(('broker_execution_id', ''), _negated=True)), _connector='OR'), name='execution_import_requires_broker_execution_id'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('risk_currency__isnull', True), ('risk_currency__regex', '^[A-Z]{3}$'), _connector='OR'), name='journalentry_risk_currency_iso_format'),
        ),
    ]
