# Generated by Django 5.2.17 on 2026-09-25 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='journalentry_risk_currency_required_with_amount',
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='execution_currency_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('planned_risk_amount__isnull', True), ('risk_currency__isnull', True)), models.Q(('planned_risk_amount__isnull', False), ('risk_currency__isnull', False), models.Q(('risk_currency', ''), _negated=True)), _connector='OR'), name='journalentry_risk_currency_required_with_amount'),
        ),
    ]
