# Generated by Django 5.2.17 on 2026-09-22 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='opening_execution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='journal_entry', to='journal.execution'),
        ),
        migrations.AddConstraint(
            model_name='rawimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['imported', 'skipped_duplicate', 'failed'])), name='rawimportrow_status_valid'),
        ),
    ]
