# Generated by Django 5.2.17 on 2026-09-22 05:12

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journalentry_opening_execution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'base_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={'base_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'base_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='rawimportrow',
            options={'base_manager_name': 'unscoped'},
        ),
        migrations.AlterModelManagers(
            name='execution',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='importbatch',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='journalentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rawimportrow',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
