# Generated by Django 5.2.17 on 2026-09-26 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_currency_format_and_import_id_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='execution',
            name='execution_broker_dedupe',
        ),
        migrations.RemoveConstraint(
            model_name='rawimportrow',
            name='rawimportrow_status_valid',
        ),
        migrations.AddField(
            model_name='execution',
            name='broker_trade_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rawimportrow',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('skipped_duplicate', 'Skipped (duplicate)'), ('failed', 'Failed'), ('skipped_conflict', 'Skipped (conflict)')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_execution_id__isnull', False), models.Q(('broker_execution_id', ''), _negated=True)), fields=('user', 'broker', 'broker_account_label', 'broker_execution_id'), name='execution_broker_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('broker_trade_id__isnull', True), models.Q(('broker_trade_id', ''), _negated=True), _connector='OR'), name='execution_broker_trade_id_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='rawimportrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['imported', 'skipped_duplicate', 'failed', 'skipped_conflict'])), name='rawimportrow_status_valid'),
        ),
    ]
