# Generated by Django 5.2.17 on 2026-09-25 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journalentry_journalentry_risk_currency_required_with_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='execution',
            name='execution_broker_dedupe',
        ),
        migrations.RemoveConstraint(
            model_name='execution',
            name='execution_price_nonnegative',
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_execution_id__isnull', False), models.Q(('broker_execution_id', ''), _negated=True)), fields=('user', 'broker', 'broker_execution_id'), name='execution_broker_dedupe'),
        ),
    ]
