# Generated by Django 5.2.17 on 2026-09-22 05:14

import django.db.models.expressions
import journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_execution_options_alter_importbatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='raw_file',
            field=models.BinaryField(validators=[journal.models.validate_raw_file_size]),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=django.db.models.expressions.RawSQL('octet_length(raw_file) <= %s', (10485760,), output_field=models.BooleanField()), name='importbatch_raw_file_size_limit'),
        ),
    ]
