# Generated by Django 5.2.17 on 2026-09-30 01:45

from django.db import migrations, models


# ADR-0007 J1 + follow-ups rows 11/14. No data is rewritten. AddConstraint validates
# existing rows, so `migrate` FAILS LOUDLY if any journalentry has planned_risk_amount
# <= 0; fix those rows by hand first. Dropped CHECKs are redundant: the *_iso_format
# regex CHECKs (^[A-Z]{3}$) already reject ''. Rollback: `migrate journal 0003`
# (reverse re-creates the dropped CHECKs; fails only if a blank currency exists,
# which the regex CHECK already prevents).
class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_topstep_dedupe_account_label"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="execution",
            name="execution_currency_not_blank",
        ),
        migrations.RemoveConstraint(
            model_name="journalentry",
            name="journalentry_risk_currency_required_with_amount",
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("planned_risk_amount__isnull", True),
                        ("risk_currency__isnull", True),
                    ),
                    models.Q(
                        ("planned_risk_amount__isnull", False),
                        ("risk_currency__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="journalentry_risk_currency_required_with_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned_risk_amount__isnull", True),
                    ("planned_risk_amount__gt", 0),
                    _connector="OR",
                ),
                name="journalentry_planned_risk_positive",
                violation_error_message="Planned risk must be greater than zero.",
            ),
        ),
    ]
