# Generated by Django 5.2.17 on 2026-09-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_importbatch_raw_file_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journalentry',
            name='journalentry_not_journaled_idx',
        ),
    ]
