# Generated by Django 5.2.17 on 2026-09-22 08:16

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_journalentry_journalentry_not_journaled_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelOptions(
            name='rawimportrow',
            options={'base_manager_name': 'unscoped', 'default_manager_name': 'unscoped'},
        ),
        migrations.AlterModelManagers(
            name='execution',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='importbatch',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='journalentry',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rawimportrow',
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
