# Generated by Django 5.2.17 on 2026-09-22 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_execution_options_alter_importbatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('contract_multiplier__gt', 0)), name='execution_contract_multiplier_positive'),
        ),
    ]
