# Generated by Django 5.2.17 on 2026-09-26 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base_currency',
            field=models.CharField(default='USD', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Currency must be a 3-letter uppercase ISO 4217 code, e.g. USD.')]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('base_currency__regex', '^[A-Z]{3}$')), name='accounts_user_base_currency_iso_format'),
        ),
    ]
