"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Fail closed: an unset/misconfigured DJANGO_DEBUG on a real deployment must not
# silently turn DEBUG on. Dev sets DJANGO_DEBUG=true explicitly (.env.example).
# Computed before SECRET_KEY below, which needs to know this to fail closed too.
DEBUG = os.environ.get('DJANGO_DEBUG', 'false').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# Fail closed (round-5 code review): DEBUG and ALLOWED_HOSTS already fail closed when
# their env vars are unset, but SECRET_KEY fell back to a hardcoded, publicly-committed
# dev value unconditionally — if prod's .env is missing DJANGO_SECRET_KEY, the app would
# silently boot with a key anyone reading this public repo can use to forge sessions,
# CSRF tokens, and password-reset tokens. The dev fallback is now only used when
# DEBUG=True; a real deployment (DEBUG=False) with no DJANGO_SECRET_KEY refuses to start.
#
# Round-7 addendum: emptiness isn't the only bad value. .env.example ships a placeholder
# (DJANGO_SECRET_KEY=...) that LOOKS like a real value someone might miss updating when
# copying .env.example to .env — the check above only catches it being unset entirely. If
# ops sets DEBUG=false and never touches that line, the app would boot in "production
# mode" using a key that's public in this repo's git history. Reject that exact known
# placeholder too, with the same fail-closed philosophy as the empty-value check.
_ENV_EXAMPLE_PLACEHOLDER_SECRET_KEY = 'CHANGE-ME-run-get_random_secret_key'

_secret_key = os.environ.get('DJANGO_SECRET_KEY')
# Round-8 code review: broadened beyond the one exact placeholder above. Any value
# starting with "django-insecure-" is Django's own `startproject` default-key prefix —
# the realistic leftover-default scenario (more likely in practice than someone leaving
# the literal CHANGE-ME placeholder from .env.example in place) — so it's rejected the
# same way when DEBUG=False.
_looks_like_a_leftover_default = bool(_secret_key) and _secret_key.startswith(
    'django-insecure-'
)
if not _secret_key or _secret_key == _ENV_EXAMPLE_PLACEHOLDER_SECRET_KEY or _looks_like_a_leftover_default:
    if DEBUG:
        # ponytail: dev-only fallback so `runserver`/tests work with zero setup; prod
        # sets DJANGO_SECRET_KEY via the VPS .env per ADR-0002 and must not use this.
        _secret_key = 'django-insecure-hx4@t%@gbhr)_sk5)rregy-%b$#z50r0vonm0k5=s^4s-mh)g@'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set to a real secret when DEBUG is False — it is '
            'either unset, still a known placeholder value, or still has the '
            '"django-insecure-" prefix Django\'s startproject generates by default. '
            'Refusing to start with a key that is public (or looks like a forgotten '
            'default) on what looks like a real deployment.'
        )
SECRET_KEY = _secret_key

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/trades/'
LOGOUT_REDIRECT_URL = '/login/'

# auth.E003 is a false positive here: it only recognizes unique=True or a plain-field
# UniqueConstraint on USERNAME_FIELD, not accounts.User's expression-based
# UniqueConstraint(Lower("email"), ...), which is a *stricter* guarantee (case-insensitive)
# than what the check looks for. See ADR-0003 §1 ("lower(email) is an acceptable
# substitute" for CITEXT) and accounts/models.py. Not worth a custom system check for
# this one remaining item.
#
# models.W045 no longer needed here (round-8 code review): journal.ImportBatch.raw_file's
# size-cap CHECK constraint used to use RawSQL("octet_length(raw_file) <= %s", ...), which
# Django's checker couldn't introspect. Replaced with Length(raw_file) <= N — an ORM
# expression Django CAN verify — so the warning doesn't fire at all anymore, root cause
# fixed rather than worked around. See journal/models.py.
SILENCED_SYSTEM_CHECKS = ['auth.E003']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'journal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'trading_journal'),
        'USER': os.environ.get('POSTGRES_USER', 'trading_journal'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'trading_journal'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # static/css/app.css is built by scripts/tailwind.sh
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target (prod image build, ADR-0002)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
