"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Fail closed: an unset/misconfigured DJANGO_DEBUG on a real deployment must not
# silently turn DEBUG on. Dev sets DJANGO_DEBUG=true explicitly (.env.example).
# Computed before SECRET_KEY below, which needs to know this to fail closed too.
DEBUG = os.environ.get('DJANGO_DEBUG', 'false').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# Fail closed (round-5 code review): DEBUG and ALLOWED_HOSTS already fail closed when
# their env vars are unset, but SECRET_KEY fell back to a hardcoded, publicly-committed
# dev value unconditionally — if prod's .env is missing DJANGO_SECRET_KEY, the app would
# silently boot with a key anyone reading this public repo can use to forge sessions,
# CSRF tokens, and password-reset tokens. The dev fallback is now only used when
# DEBUG=True; a real deployment (DEBUG=False) with no DJANGO_SECRET_KEY refuses to start.
_secret_key = os.environ.get('DJANGO_SECRET_KEY')
if not _secret_key:
    if DEBUG:
        # ponytail: dev-only fallback so `runserver`/tests work with zero setup; prod
        # sets DJANGO_SECRET_KEY via the VPS .env per ADR-0002 and must not use this.
        _secret_key = 'django-insecure-hx4@t%@gbhr)_sk5)rregy-%b$#z50r0vonm0k5=s^4s-mh)g@'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DEBUG is False. Refusing to start with '
            'the public dev fallback key on what looks like a real deployment.'
        )
SECRET_KEY = _secret_key

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

AUTH_USER_MODEL = 'accounts.User'

# auth.E003 is a false positive here: it only recognizes unique=True or a plain-field
# UniqueConstraint on USERNAME_FIELD, not accounts.User's expression-based
# UniqueConstraint(Lower("email"), ...), which is a *stricter* guarantee (case-insensitive)
# than what the check looks for. See ADR-0003 §1 ("lower(email) is an acceptable
# substitute" for CITEXT) and accounts/models.py.
# models.W045: journal.ImportBatch.raw_file's size-cap CHECK constraint uses RawSQL
# (octet_length), which Django can't pre-validate in full_clean(). Expected and covered:
# the field's own max_length= gives it Django's built-in MaxLengthValidator, which
# handles the full_clean() path, and the DB constraint is the backstop for every other
# write path. See journal/models.py (stale reference to a since-removed hand-written
# validate_raw_file_size validator corrected here, round-5 code review).
SILENCED_SYSTEM_CHECKS = ['auth.E003', 'models.W045']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'journal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'trading_journal'),
        'USER': os.environ.get('POSTGRES_USER', 'trading_journal'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'trading_journal'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
